"""Add session table

Revision ID: b0ca57e15d72
Revises: 9904805ccf70
Create Date: 2026-02-13 11:54:22.978950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0ca57e15d72'
down_revision: Union[str, Sequence[str], None] = '9904805ccf70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('access_jti', sa.VARCHAR(length=255), nullable=False),
    sa.Column('refresh_jti', sa.VARCHAR(length=255), nullable=False),
    sa.Column('access_token', sa.TEXT(), nullable=False),
    sa.Column('refresh_token', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_access_jti'), 'sessions', ['access_jti'], unique=True)
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_is_active'), 'sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_sessions_refresh_jti'), 'sessions', ['refresh_jti'], unique=True)
    op.create_index(op.f('ix_sessions_user_uid'), 'sessions', ['user_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_uid'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_refresh_jti'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_is_active'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_access_jti'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
